// JScript 文件
function orderSearch(trackNum,carrier)
{
if(trackNum.length <= 0)
{
    alert("请输入运单号！");
    return;
}
url="";
if(carrier=="hk")
{
url="http://app3.hongkongpost.com/CGI/mt/c_genresult.jsp?tracknbr="+trackNum;
window.open(url);
}
if(carrier=="ems")
{
url="http://www.ems.com.cn/qcgzOutQueryNewAction.do?myEmsbarCode=1&reqCode=browseBASE&mailNum="+trackNum;
window.open(url);
}
if(carrier=="yzdb")
{
url="http://intmail.183.com.cn/item/itemStatusQuery.do?itemNo="+trackNum;
window.open(url);
}
if(carrier=="cp")
{
url="http://intmail.183.com.cn/item/itemStatusQuery.do?itemNo="+trackNum;
window.open(url);
}
if(carrier=="ups")
{
url="http://wwwapps.ups.com/WebTracking/track?loc=zh_HK&trackNums="+trackNum;
window.open(url);
}
if(carrier=="fedex")
{
url="http://www.fedex.com/Tracking?ascend_header=1&clienttype=dotcomreg&cntry_code=cn&language=sim&tracknumbers="+trackNum;
window.open(url);
}
if(carrier=="gda")
{
url="http://www.gdalliance.com/Track/Track.aspx"
window.open(url);
}
if(carrier=="dhl")
{
url="http://www.cn.dhl.com/zh/express/trackNum.html"
window.open(url);
}
if(carrier=="citylink")
{
url="http://www.citylinkexpress.com/CN/zh-CN/shipmenttracking.aspx?cno="+trackNum;
window.open(url);
}
if(carrier=="usps")
{
url="http://trkcnfrm1.smi.usps.com/PTSInternetWeb/InterLabelInquiry.do?strOrigTrackNum="+trackNum;
window.open(url);
}
if(carrier=="tnt")
{
url="http://www.tnt.com/webtracker/tracker.do?navigation=1&respLang=zh&respCountry=cn"
window.open(url);
}
if(carrier=="zokdyg")
{
url="http://www.hdnl.co.uk"
window.open(url);
}
if(carrier=="dragonlink")
{
url="http://www.dragonlink.net"
window.open(url);
}
return;
} 
